//! The post-save confirmation chime.
//!
//! Played from Rust, at the same dispatch point the preview uses, for two
//! reasons the webviews cannot satisfy: the sound must be heard while every
//! Encore window is hidden (menu-bar mode) and while another application
//! holds focus, and an unfocused/hidden webview is an unreliable audio
//! source under autoplay policy. Playback is handed to a detached thread so
//! the save path is never delayed by it.
//!
//! The asset is ours: `resources/save-chime.wav`, a ~0.3s two-tone chime
//! generated by `scripts/generate-save-chime.mjs` and bundled through
//! `tauri.conf.json`'s `bundle.resources`. Nothing here touches the network
//! and no system sound path is depended on.

use std::{path::PathBuf, process::Command, thread};
use tauri::{path::BaseDirectory, AppHandle, Manager};

const ASSET: &str = "resources/save-chime.wav";

/// Plays the chime when `enabled`, and does nothing at all otherwise.
///
/// Only ever called for a save that reached the `saved` state, so a failed
/// save stays silent by construction. Every failure is swallowed: a missing
/// asset or an unavailable player must not disturb a save that already
/// succeeded.
pub(crate) fn play_saved_chime(app: &AppHandle, enabled: bool) {
    if !enabled {
        return;
    }
    let Some(path) = asset_path(app) else {
        return;
    };
    // `afplay` is the dependency-free macOS route. The thread waits on the
    // child (reaping it) while the caller returns immediately, so playback
    // neither blocks the save nor leaves a zombie behind.
    thread::spawn(move || {
        let _ = Command::new("afplay").arg(path).status();
    });
}

/// The first candidate that exists on disk. Bundled builds resolve inside
/// the app's `Resources` directory; `resolve` also answers in dev, where
/// Tauri stages bundle resources next to the debug binary, and the source
/// tree is kept as a last-resort dev fallback so a stale target directory
/// cannot silence the chime.
fn asset_path(app: &AppHandle) -> Option<PathBuf> {
    candidates(app).into_iter().find(|path| path.is_file())
}

fn candidates(app: &AppHandle) -> Vec<PathBuf> {
    let mut candidates = Vec::new();
    if let Ok(resolved) = app.path().resolve(ASSET, BaseDirectory::Resource) {
        candidates.push(resolved);
    }
    #[cfg(debug_assertions)]
    candidates.push(PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(ASSET));
    candidates
}

#[cfg(test)]
mod tests {
    use super::ASSET;
    use std::path::PathBuf;

    /// The bundled asset must actually be in the source tree: the config
    /// entry and the resolution above are both worthless without it, and a
    /// missing file would only ever show up as silence at runtime.
    #[test]
    fn the_chime_ships_with_the_source_tree() {
        let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(ASSET);
        let bytes = std::fs::metadata(&path).map(|meta| meta.len()).unwrap_or(0);
        assert!(bytes > 0, "missing chime asset at {}", path.display());
        assert!(bytes < 30_000, "chime asset grew to {bytes} bytes");
    }
}
